api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "price-threshold"
type = "function"
uid = "b5b4e9a6-cf94-357d-7711-2cd9fd758141e08347d0"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
