query CartDeliveryOptionsTransformRunInput {
  cart {
    attribute(key: "igTestGroups") {
      key
      value
    }
    cost {
      subtotalAmount {
        amount
      }
    }
    deliveryGroups {
      deliveryAddress {
        countryCode
        provinceCode
      }
      deliveryOptions {
        handle
        cost {
          amount
        }
      }
    }
  }
  deliveryCustomization {
    metafield(
      namespace: "$app:shipping-threshold"
      key: "function-configuration"
    ) {
      jsonValue
    }
  }
}
